---
- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    id: 46095ACC8548582C1A2699A9D27D666CD88E42B4
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/8.x/apt stable main'
    state: present

- name: SSL cert for Logz.io.
  include_tasks: logzio.yaml
  when: "'infra' in ansible_run_tags"

- name: Install Filebeat
  include_tasks: filebeat.yaml
  tags: global

- name: Install Auditbeat
  include_tasks: auditbeat.yaml
  when: "'infra' in ansible_run_tags"
