- name: Deploy Defender ATP
  hosts: all
  become: true
  tasks:
    - name: Install unzip
      apt:
        pkg: unzip
    - name: Create MDATP directories
      file:
        path: /etc/opt/microsoft/mdatp/
        recurse: true
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Register mdatp_onboard.json
      stat:
        path: /etc/opt/microsoft/mdatp/mdatp_onboard.json
      register: mdatp_onboard

    - name: Extract WindowsDefenderATPOnboardingPackage.zip into /etc/opt/microsoft/mdatp
      unarchive:
        src: files/WindowsDefenderATPOnboardingPackage.zip
        dest: /etc/opt/microsoft/mdatp
        mode: 0600
        owner: root
        group: root
      when: not mdatp_onboard.stat.exists
    
    - name: Add Microsoft APT key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Microsoft apt repository for MDATP
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.04/prod.list
        dest: /etc/apt/sources.list.d/microsoft-prod.list
        force: true

    - name: Install MDATP
      apt:
        name: mdatp
        state: latest
        update_cache: yes
