# roles/base/tasks/main.yml
#- name: Apply the latest CIS hardening
#  import_tasks: hardening.yaml
#  tags: global

#- name: Install and configure Filebeat and Auditbeat
#  import_tasks: beats.yaml
#  tags: global

- name: Set the SSHD permissions
  import_tasks: sshd.yaml
  tags: global
  
- name: Add sherweb disclaimers
  import_tasks: sherweb.yaml
  tags: global

- name: Apply the default firewall rules
  import_tasks: ufw.yaml
  tags: global
  
- name: Install snmpd and create PRTG user
  import_tasks: snmpd.yaml
  tags: global

# TO DO
#- name: Install and configure Windows Defender
#  import_tasks: defender.yaml
#  tags: global

#- name: Configure PRTG sensors
#  import_tasks: monitoring.yaml
#  tags: infra

#- name: Set the NTP servers
#  import_tasks: ntp.yaml
#  tags: global

#- name: Apply domain authentication
#  import_tasks: sssd.yaml
#  tags: global

#- name: Install and configure Tenable
#  import_tasks: tenable.yaml
#  tags: global
