- name: Add Sherweb disclaimer to /etc/update-motd.d/99-motd-sherweb
  template:
    src: "../templates/motd-sherweb.j2"
    dest: "/etc/update-motd.d/99-motd-sherweb"
    owner: root
    group: root
    mode: 0755

- name: Add Sherweb disclaimer to /etc/issue
  template:
    src: "../templates/issue-sherweb.j2"
    dest: "/etc/issue"
    owner: root
    group: root
    mode: 0644

- name : Add Sherweb disclaimer to /etc/issue.net
  template:
    src: "../templates/issue-net-sherweb.j2"
    dest: "/etc/issue.net"
    owner: root
    group: root
    mode: 0644
