- name: Add Sherweb disclaimer to /etc/motd
  template:
    src: "../templates/motd_sherweb.j2"
    dest: "/etc/update-motd.d/99-motd-sherweb"
    owner: root
    group: root
    mode: 0755

- name: Add Sherweb disclaimer to /etc/issue
  template:
    src: "../templates/issue_sherweb.j2"
    dest: "/etc/issue"
    owner: root
    group: root
    mode: 0644

- name: Add Sherweb disclaimer to /etc/issue.net
  copy:
    content: "{{ issue_net_sherweb }}"
    dest: "/etc/issue.net"

- name : Set disclaimer permissions
  template:
    src: "../templates/issue_net_sherweb.j2"
    dest: "/etc/issue.net"
    owner: root
    group: root
    mode: 0644
