---
- name: Install snmpd.
  package:
    name: snmpd
    state: present

- name: Copy snmpd configuration.
  template:
    src: "../templates/snmpd.conf.j2"
    dest: "/etc/snmp/snmpd.conf"
    owner: root
    group: root
    mode: 0600

- name: Stop snmpd for user creation
  service:
    name: snmpd
    state: stopped

- name: Create PRTG user
  shell: "net-snmp-create-v3-user -ro -A "{{ snmpd_password }}" -a SHA -X "{{ snmpd_password }}" -x AES "{{ snmpd_user }}""

- name: Ensure snmpd is started and enabled at boot.
  service:
    name: snmpd
    state: started
    enabled: true
