---
- name: Install snmpd.
  package:
    name: snmpd
    state: present

- name: Stop snmpd for user creation
  service:
    name: snmpd
    state: stopped

- name: Create PRTG user
  shell: "net-snmp-create-v3-user -ro -A {{ snmpd_password }} -a SHA -X {{ snmpd_password }} -x AES {{ snmpd_user }}"

- name: Ensure snmpd is started and enabled at boot.
  service:
    name: snmpd
    state: started
    enabled: true
