---
- name: SSHD Add hostkey directive for ed25519
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#HostKey "
    line: HostKey /etc/ssh/ssh_host_ed25519_key

- name: SSHD Add hostkey directive for rsa
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#HostKey "
    line: HostKey /etc/ssh/ssh_host_rsa_key

- name: SSHD Configure SyslogFacility
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?SyslogFacility"
    insertafter: "^# Logging"
    line: SyslogFacility AUTHPRIV

- name: SSHD Configure LogLevel
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?LogLevel"
    insertafter: "^# Logging"
    line: LogLevel INFO

- name: SSHD Configure LoginGraceTime
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?LoginGraceTime"
    insertafter: "^# Authentication"
    line: LoginGraceTime 60

- name: SSHD Configure PermitRootLogin
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitRootLogin"
    insertafter: "^# Authentication"
    line: PermitRootLogin no

- name: SSHD Configure StrictModes
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?StrictModes"
    insertafter: "^# Authentication"
    line: StrictModes yes

- name: SSHD Configure MaxAuthTries
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?MaxAuthTries"
    insertafter: "^# Authentication"
    line: MaxAuthTries 4

- name: SSHD Configure MaxSessions
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?MaxSessions"
    insertafter: "^# Authentication"
    line: MaxSessions 4

- name: SSHD Configure PubkeyAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PubkeyAuthentication"
    insertafter: "^# Authentication"
    line: PubkeyAuthentication yes

- name: SSHD Configure AuthorizedKeysFile
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AuthorizedKeysFile"
    insertafter: "^# Authentication"
    line: AuthorizedKeysFile  .ssh/authorized_keys

- name: SSHD Configure AuthorizedKeysCommand
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AuthorizedKeysCommand"
    insertafter: "^# Authentication"
    line: AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys

- name: SSHD Configure AuthorizedKeysCommandUser
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AuthorizedKeysCommandUser"
    insertafter: "^# Authentication"
    line: AuthorizedKeysCommandUser root

- name: SSHD Configure HostbasedAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?HostbasedAuthentication"
    insertafter: "^# Authentication"
    line: HostbasedAuthentication no

- name: SSHD Configure IgnoreRhosts
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?IgnoreRhosts"
    insertafter: "^# Authentication"
    line: IgnoreRhosts yes

- name: SSHD Configure PermitEmptyPasswords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitEmptyPasswords"
    insertafter: "^# Authentication"
    line: PermitEmptyPasswords no

- name: SSHD Configure PasswordAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PasswordAuthentication"
    insertafter: "^# Authentication"
    line: PasswordAuthentication yes

- name: SSHD Configure ChallengeResponseAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ChallengeResponseAuthentication"
    insertafter: "^# Authentication"
    line: ChallengeResponseAuthentication no

- name: SSHD Configure KerberosAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?KerberosAuthentication"
    insertafter: "^# Kerberos options"
    line: KerberosAuthentication no

- name: SSHD Configure GSSAPIAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?GSSAPIAuthentication"
    insertafter: "^# GSSAPI options"
    line: GSSAPIAuthentication no

- name: SSHD Configure GSSAPICleanupCredentials
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?GSSAPICleanupCredentials"
    insertafter: "^# GSSAPI options"
    line: GSSAPICleanupCredentials yes

- name: SSHD Configure UsePAM
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?UsePAM"
    insertafter: "^# GSSAPI options"
    line: UsePAM yes

- name: SSHD Configure AllowTcpForwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AllowTcpForwarding"
    insertafter: "^# GSSAPI options"
    line: AllowTcpForwarding no

- name: SSHD Configure X11Forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?X11Forwarding"
    insertafter: "^# GSSAPI options"
    line: X11Forwarding no

- name: SSHD Configure PermitUserEnvironment
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?PermitUserEnvironment"
    insertafter: "^# GSSAPI options"
    line: PermitUserEnvironment no

- name: SSHD Configure ClientAliveInterval
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveInterval"
    insertafter: "^# GSSAPI options"
    line: ClientAliveInterval 0

- name: SSHD Configure ClientAliveCountMax
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?ClientAliveCountMax"
    insertafter: "^# GSSAPI options"
    line: ClientAliveCountMax 60

- name: SSHD Configure UseDNS
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?UseDNS"
    insertafter: "^# GSSAPI options"
    line: UseDNS no

- name: SSHD Configure MaxStartups
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?MaxStartups"
    insertafter: "^# GSSAPI options"
    line: MaxStartups 10:30:60

- name: SSHD Configure Banner
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Banner"
    insertafter: "^# no default banner path"
    line: Banner /etc/issue.net

- name: SSHD Configure AcceptEnv line 1
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?AcceptEnv"
    insertafter: "^# Allow client to pass"
    line: AcceptEnv LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES

- name: SSHD Add AcceptEnv line 2
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#?AcceptEnv"
    line: AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT

- name: SSHD Add AcceptEnv line 3
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#?AcceptEnv"
    line: AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE

- name: SSHD Add AcceptEnv line 4
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#?AcceptEnv"
    line: AcceptEnv XMODIFIERS

- name: SSHD Configure Subsystem
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Subsystem"
    insertafter: "^# override default of no subsystems"
    line: sftp    /usr/libexec/openssh/sftp-server

- name: SSHD Configure AllowGroups
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    line: AllowGroups {{ linux_groups }}

- name: SSHD Configure Match
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    line: Match User nessus\n   PasswordAuthentication no\n   AuthenticationMethods publickey\n

- name: SSHD Configure Ciphers
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    line: Ciphers aes256-ctr, aes192-ctr, aes128-ctr

- name: SSHD Add comment for MACs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertbefore: "^Ciphers"
    line: "# CIS 5.1.6 Ensure sshd Ciphers are configured (Scored)"

- name: SSHD Configure MACs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: EOF
    line: MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

- name: SSHD Add comment for MACs
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    insertbefore: "^MACs"
    line: "# CIS 5.1.15 Ensure sshd MACs are configured (Scored)"
