---
- name: Allow SSH 22/tcp inbound traffic
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "22"
- name: Allow snmp 161/udp inbound traffic
  community.general.ufw:
    rule: allow
    proto: udp
    port: "161"

- name : Enable UFW
  community.general.ufw:
  state: enabled
