---
beat_version: 8.x
beat_package_state: present

auditbeat_package: filebeat
filebeat_package: filebeat


beat_create_config: true
auditbeat_template: "auditbeat.yml.j2"
filebeat_template: "filebeat.yml.j2"
