---
-   name: sample book
    hosts: infrastructure
    connection: local
    become: true
    tasks:
        - name: create content
          copy:
            content: "hello world"
            dest: /var/www/html/index.html
